### ISSUE TITLE
BUG: nix installation error

### ISSUE THREAD

**Issue by fedoranvar** [hyprland-community/hypract#2]
Good day to you!

was trying install or run it in nix-way, but got an error:

via home-manager:
![image](https://github.com/hyprland-community/hypract/assets/52028706/399d1f0c-2759-479c-b7ec-1b40201575c5)

via nix-run:
![image](https://github.com/hyprland-community/hypract/assets/52028706/0027e9b4-bd03-4f82-816c-4d0760f9b1e9)

**Comment by yavko** [comment]
> Good day to you!
> 
> was trying install or run it in nix-way, but got an error:
> 
> via home-manager: ![image](https://private-user-images.githubusercontent.com/52028706/291094780-399d1f0c-2759-479c-b7ec-1b40201575c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxNTAwNTgsIm5iZiI6MTcwNDE0OTc1OCwicGF0aCI6Ii81MjAyODcwNi8yOTEwOTQ3ODAtMzk5ZDFmMGMtMjc1OS00NzljLWI3ZWMtMWI0MDIwMTU3NWM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDIyNTU1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkMWM4ZDM2ZTQ5YjYyZDNjNzMxMTg0ZTA2ZDVjMDYzYmVlM2MwMWM4OTJmMjAzNjExMzFjYTNkZTVjMWUxMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l85BDqgjLAbJOVOeVmofktlI8gBXZXd6YQc7zp5986c)
> 
> via nix-run: ![image](https://private-user-images.githubusercontent.com/52028706/291094790-0027e9b4-bd03-4f82-816c-4d0760f9b1e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxNTAwNTgsIm5iZiI6MTcwNDE0OTc1OCwicGF0aCI6Ii81MjAyODcwNi8yOTEwOTQ3OTAtMDAyN2U5YjQtYmQwMy00ZjgyLTgxNmMtNGQwNzYwZjliMWU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDIyNTU1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2MWMxNTdiOTc3Y2ExODUxZjQ5MjgzMDgzYWJlYzYwYTE0OWIxMmY1ZGI3YTE2OGQwZWVjNmYzNTNiNzY1M2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3U_LSOBC2udYQ7-tHBXs5Q_3JWRUp82S8yEYGzA0LFU)

weird, ill look into this soon

**Comment by yavko** [comment]
@fedoranvar i updated the libraries, try again maybe? CI shows no errors

**Comment by fedoranvar** [comment]
yes, problem fixed

thank you!
